//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jeecup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeecup_tbl
    {
        public int ID { get; set; }
        public string CandidateName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string AadhaarConsent { get; set; }
        public string ISDCode { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityPin { get; set; }
    }
}
